### ISSUE TITLE
Look at using python-docx

### ISSUE THREAD

**Issue by wichert** [euphorie/Euphorie#103]
It might be interesting to use [python-docx](https://github.com/python-openxml/python-docx) to create docx files instead of the current RTF scheme.

**Comment by pysailor** [comment]
python-docx is now being used in a custom version of Euphorie (for an industry client) to fill a custom Word template. 
This mechanism (using a generic template) will be ported to Euphorie in the next months. It adds the possibility for having different Word templates per country, so that local legal requirements / preferences can be supported.

**Comment by pysailor** [comment]
Fixed by #173
