### ISSUE TITLE
Obsolete-survey checkbox should be exposed in survey edit screen

### ISSUE THREAD

**Issue by wichert** [euphorie/Euphorie#106]
Currently the only way to get to the checkbox is to manually change the URL so you are editing the survey group.

**Comment by wichert** [comment]
@pilz Can you provide a planning when this can be fixed?

**Comment by pilz** [comment]
Ideally Wolfgang would do this who is on holidays until 5.2. 
I believe that he should be able to do this in the week after (ca. 12.2.).

**Comment by pysailor** [comment]
@wichert Now that I have a running installation of tno.euphorie, I see the problem. There's a redirect from the survey group to the survey, something which is not present in OiRA.
I assume this redirect needs to be kept, since the RI&E users are used to it, resulting in this request for a workaround?

**Comment by wichert** [comment]
There is no reason for a user to every visit the survey group itself, which is why the redirect is in place. So I do not see this as a workaround - I see this as a fix for a UX bug.

**Comment by pysailor** [comment]
ok, sure
